# Generated by Django 5.2.1 on 2025-05-18 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(help_text='O telefone deve seguit o formato (00)00000-0000', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='Formato (00)00000-0000', regex='^\\(\\d{2}\\)\\d{5}-\\d{4}$')]),
        ),
    ]
