# Generated by Django 5.2.1 on 2025-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
